language: node_js
node_js:
  - "8.12"
sudo: false
env:
  - NODE_ENV='test'
script:
  - yarn install
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_install:
        - openssl aes-256-cbc -K $encrypted_81656b5e166a_key -iv $encrypted_81656b5e166a_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - nvm install node
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
      install:
        - yarn install --frozen-lockfile
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-27
      script:
        - yarn buildDev
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      node_js: false
      before_install:
        - nvm install node
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
        - wget https://dl.google.com/firebase/sdk/ios/5_12_0/Firebase-5.12.0.zip
        - unzip -q Firebase-5.12.0.zip -d ios
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn install --frozen-lockfile
      xcode_project: ios/mapswipe.xcodeproj
      xcode_scheme: ios/mapswipeTests
      script:
        - cd ios
        - xcodebuild -scheme mapswipe -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - travis_retry xctool run-tests -scheme mapswipe -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
